markdown: kramdown
# baseurl: /mar
exclude: ['README.md','vendor']
permalink: pretty
plugins:
  - jekyll-seo-tag
author: Marius Valaitis
defaults:
    -
     scope:
         path: ""
     values:
         author: "me"
         layout: myLayout
         lang: lt
         base-url: "/"
    -
     scope:
         path: en
     values:
         lang: en
         base-url: "/en/"

theme: jekyll-theme-clean-blog
future: true